---
output:
  word_document:
    reference_docx: myref.docx
---



```{r setup, include = F}

rm(list=ls())

#Load knitr
library(knitr)

#Set some options
options(na.action='na.fail')
opts_knit$set(root.dir = '..')
opts_chunk$set(echo=FALSE,
               warning=FALSE,
               message=FALSE,
               fig.path='../Figures/',
               fig.width= 4,
               fig.height= 8,
               fig.show='asis',
               dev='png')

```

```{r load and clean, include = F}

#Load and clean data
source('Scripts/Telomere parentage LOAD.r')
source('Scripts/Telomere parentage FUNCTIONS.r')
source('Scripts/Telomere parentage CLEAN.r')


```




**Table S1** Generalised linear mixed model output for analysis of parental condition on offspring sex ratio. We report...

```{r Table S1}

#Sex ratio and parental adult TL
sr_LmumTL <- glmer(SexEstimate ~  LmumTL + mumage + Fledged + TQ + Helper + (1|mother) + (1|LayYear),data = juv,family = 'binomial',na.action=na.exclude)
sr_LdadTL <- glmer(SexEstimate ~ LdadTL  + dadage + Fledged + TQ + Helper + (1|father) + (1|LayYear),data = juv,family = 'binomial',na.action=na.exclude)



```



